typography_spectrum: 0.835978769975447
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.5370648528105294
  lightness: 0.31042601078887017
  saturation: 0.7546060016162066
  rhythmicContrast: 0.006612309012654247
github: true
opengraph:
  type: 'https://www.facebook.com/ArtificialxIntelligence/'
  appId: '687680154650184'
layout_spectrum: 0.8268744277134353
analytics:
  twitter: Global X
  facebook: ' 561356607354344'
  google: UA-111390797-1
author:
  name: Ewa Tchorzewska
  email: office@globalx.pl
  url: 'http://www.globalx.pl/'
name: Global X Solutions
url: 'http://www.globalxsolutions.org/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: CoBe Therapy ....about depresion
    url: 'http://cobetherapy.com/'
    type: external
title: Global X Solutions
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/eb9eeaf5-edb4-4089-aa81-aafb053b86cc.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/eb9eeaf5-edb4-4089-aa81-aafb053b86cc.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/dcdc9c57-30ee-41e5-965f-d8fbdfe5af38.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/dcdc9c57-30ee-41e5-965f-d8fbdfe5af38.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Investing in Tomorrow's Leaders
purpose:
  - type: contact
    url: 'tel:+48789421478'
    label: Call +48789421478
  - type: external
    url: 'http://www.globalx.pl/'
    label: 'http://www.globalx.pl/'
